# scripts/generate-env-paths.nu
# Usage: nu scripts/generate-env-paths.nu > /tmp/generated-nix-paths.nu
# MUST be run *inside* nix develop so tool paths are correct

let tools = [ 'bat' 'eza' 'rg' 'fd' 'sd' 'delta' 'dust' 'procs' 'btm' 'xh' 'zoxide' 'hyperfine' 'tokei' 'just' 'jj' 'nu' 'starship' 'npm' 'npx' 'uv' 'hx' ]

let paths = (
    $tools | each {|tool| 
        let path = (which $tool | get path.0? | default null)
        if $path == null {
            error make {msg: ($tool + " missing from PATH — maybe missing from flake.nix?")}
        }
        ($path | path dirname)
    }
)

# Only keep unique directories and preserve order
let unique_paths = ($paths | uniq)

print "# --- generated by scripts/generate-env-paths.nu inside nix develop ---\n"
print "$env.PATH = ("
print "    $env.PATH"
print "    | split row (char esep)"
$unique_paths | each {|p| print ("    | prepend \"" + $p + "\"") }
print "    | uniq"
print "    | uniq"
print "    | str collect (char esep)"
print ")\n"
